#!/usr/bin/env python3
# Lambda function to return a webpage

def handle_request(event, context):

    # body here is a string
    # but obviously can be generated by any process!
    body = '<!DOCTYPE html><html><head><body><h1>This is a test.</h1></body></html>'

    # return dictionary must have this structure
    # content-type needed to switch browser to HTML mode
    return {
        "statusCode": 200,
        "headers": {
            "content-type": "text/html",
            },
        "body": body
        }

